### ISSUE TITLE
Hi I would like to help finish this project, but I am facing issues trying to understand the true nature of it

### ISSUE THREAD

**Issue by CorruptedSpring** [kimght/LimbusStory#13]
Can you guys please explain what this repo is exactly? I understood that this is about a story. But what exactly?
Note: I don't talk Russian, but I am willing to help.

**Comment by kimght** [comment]
Hi! This repo contains the RU localization files for the visual novel part of the game in a human-readable and translation-friendly format, which you might find in the `chapters` folder. If you want to contribute, you could make a fork, modify it and submit a pull request. But I believe it would be difficult if you don't know Russian.

Alternatively, you can still help other translation teams (check out other forks of [original mod](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany))!

**Comment by CorruptedSpring** [comment]
oki thank you !
